### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by kevdel** [januschung/math-worksheet-generator#11]
An option to control the number of questions presented per page e.g 4x4, 6x6, 8x8 scaled to fill the page

Option to include or exclude the answer page 

Add today's date to the top of the page

Great work! 👍

**Comment by fuatu** [comment]
This is great and thanks!
Can you also add division to the problems?

**Comment by fuatu** [comment]
@januschung if you add me as a contributor I can develop the division option as a new branch and you can merge it to master.

**Comment by januschung** [comment]
Hey @fuatu I would need a way to display it nicely with long division format before adding the function.

**Comment by fuatu** [comment]
> Hey @fuatu I would need a way to display it nicely with long division format before adding the function.

@januschung one option for you to use LaTeX and generate the doc accordingly. In that case you can use any math formatting. After you have latex text you can create pdf from it. 

Please check 
https://github.com/JelteF/PyLaTeX
https://tex.stackexchange.com/questions/131125/better-way-to-display-long-division

**Comment by januschung** [comment]
Thanks @fuatu I will check it out.

**Comment by januschung** [comment]
division has been added for a while
