### ISSUE TITLE
Add unittests to the application.. 

### ISSUE THREAD

**Issue by espoirMur** [januschung/math-worksheet-generator#19]
This is a great tool, I like it so much... Kudos!! 

I think It may be better to add some unit tests to the application to ensure that something is not broken in the process. 

I don't have time to work on that now, I am putting this issue here for my future self or any other developer who will have time. 

Keep up the good work... 

_From A fellow parent ..._

**Comment by januschung** [comment]
Thanks @espoirMur this is on my todo list.

**Comment by januschung** [comment]
Just added unittests and and pr check to the repo.
