### ISSUE TITLE
Web version of math worksheet generator

### ISSUE THREAD

**Issue by ar363** [januschung/math-worksheet-generator#39]
Can I make a web version of this math worksheet generator with Flask? It's much simpler for non tech-savvy people to generate worksheet PDFs from a website than a CLI.

I just wanted to ask you permission before I made it.

**Comment by januschung** [comment]
It is ok as long as you fork and share the work. Thanks.

**Comment by ar363** [comment]
Yes definitely, I'll preserve the GPLv2 licencse and modify the fork. Also im not planning to monetize it with any ads.

It's just a personal project

**Comment by ar363** [comment]
Thank you

**Comment by ar363** [comment]
thats all

**Comment by ar363** [comment]
I finally made it

Github: https://github.com/ar363/math-worksheet-generator-webapp
Website: https://mathsworksheetgenerator.vercel.app/
