### ISSUE TITLE
More control about Numbers used in the worksheet

### ISSUE THREAD

**Issue by mrpoet2** [januschung/math-worksheet-generator#40]
Hello,

Thank you for such a great work. It really helps a lot keeping my kids occupied.

I'm not a code developer. This may be vary obvious...

But how could I force the software when selecting to work with 2 digits only work with the range of numbers 10-99
or if selecting to work with 3 digits only work with 100-999.

I think it's this part of the code

`    # how many places, 1:0-9, 2:0-99, 3:0-999
    if args.digits == "1":
        size_ = 9
    elif args.digits == "3":
        size_ = 999
    else:
        size_ = 99`

But I don't know how to change it to do what I want. Could you help me with that? 

Best regards & Thank you again!

**Comment by januschung** [comment]
Thanks @mrpoet2 I am glad it helps. Currently there isn't an argument you can pass to make it works the way you want. However, you can play with this line to set the minimum number: https://github.com/januschung/math-worksheet-generator/blob/11aa6b2f2ecb9b5fb99ce6bc25ed8980eeeb7258/run.py#L46

For example, if you want 10-99:
num = random.randint(10, self.max_number), and then run `python3 run.py --digits 2`

Or if you want 100-999:
num = random.randint(100, self.max_number), and then run `python3 run.py --digits 3`

Hope this helps.

**Comment by mrpoet2** [comment]
Thank you very much. This helped!
