### ISSUE TITLE
Less Space Between Number 1 and Number 2

### ISSUE THREAD

**Issue by mrpoet2** [januschung/math-worksheet-generator#42]
Hello,

I'm letting my kids resolve 2-digit multiplications. However the space for them to resolve the problems is very small. I've tried changing the font size, but still.

Is there a way to move number 1 and number 2 further north in the box? Or maybe narrow the space between number 1 and number 2? Or maybe is there a way to make the box larger (to the south side)?

Whatever works easier.

Thank you very much.

**Comment by januschung** [comment]
There is no straightforward way to do it. However, you can make the question box taller by setting https://github.com/januschung/math-worksheet-generator/blob/master/run.py#L27 to 24

Also, you can play around with the second parameter in https://github.com/januschung/math-worksheet-generator/blob/master/run.py#L133-L134 and https://github.com/januschung/math-worksheet-generator/blob/master/run.py#L151-L152. 

Hope this helps.

**Comment by mrpoet2** [comment]
That helped very good however. 
I'm still looking for the part of the code responsible for the "result line" (see image attached), which I would like to move a little bit.

[https://pasteboard.co/KaNFk3H.png](url) 

Thank you!
