### ISSUE TITLE
worksheets with >3 digits

### ISSUE THREAD

**Issue by gour** [januschung/math-worksheet-generator#46]
Hello!

Haw hard/easy would be to add option to generate worksheets using >3 digits?

Sincerely

**Comment by januschung** [comment]
hey there you can fork and add some logic to enable 4 digits or more - https://github.com/januschung/math-worksheet-generator/blob/master/run.py#L281C1-L282C20

I decide not to do it since it will mess up the answer sheet format with large answer especially for multiplication.
